name: Realistic-Swimming
main: realisticSwimming.main.RSMain
version: 1.19.1
author: 4a2e532e
softdepend: [NoCheatPlus]
commands:
  rs:
    permission: rs.admin.reload
    description: 'reloads the config'
    usage: '/rs reload'
  swim:
    description: 'Enables/disables the swimming animation.'
    usage: '/swim <on/off>'
  fall:
    description: 'Enables/disables the falling animation.'
    usage: '/fall <on/off>'
permissions:
  rs.user.swim:
    default: op
  rs.user.boost:
    default: op
  rs.user.fall:
    default: op
  rs.admin.reload:
    default: op
  rs.bypass.stamina:
    default: false