name: Realistic-Swimming
main: realisticSwimming.RSMain
version: 1.11.0-SNAPSHOT
author: 4a2e532e
commands:
  rs:
    permission: rs.admin.reload
    description: 'reloads the config'
    usage: '/rs reload'
permissions:
  rs.user.swim:
    default: op
  rs.user.boost:
    default: false
  rs.admin.reload:
    default: op