name: Realistic-Swimming
main: realisticSwimming.RSMain
version: 1.9.1
author: 4a2e532e
commands:
  rs:
    permission: rs.admin.reload
permissions:
  rs.user.swim:
    default: op
  rs.user.boost:
    default: false
  rs.admin.reload:
    default: op